#! /bin/bash
test -f test2.dmg && rm test2.dmg
./create-dmg   \
	--icon-size 96  \
	--window-pos 413 295  \
	--window-size 770 367  \
	--icon Applications 527 187   \
	--volname "Songbook Client v0.x"   \
	--icon "Songbook-Client.app" 201 187  \
	--background ~/songbook-client/macos_specific/Sbc/.bg/background.png  \
	test2.dmg ~/songbook-client/build/ 
